"alloca.h" not available under win32.
Use malloc() instead of alloca() and properly free the allocated memory.
Fixes build error:
> fatal error: alloca.h: No such file or directory