Fix a "maybe non-unintialized" build case.
Actually the only code path where val16 may be uninitialized would end
up in assert(), so that's impossible. But that still broke gcc
cross-compilation here, even more since all warnings are treated as
errors. So let's just initialize the variable to something.
Fixes:
> error: 'val16' may be used uninitialized in this function [-Werror=maybe-uninitialized]