encoder: Fix unused variable error
libheif/heif_encoder_x265.cc:635:7: error: unused variable ‘s’ [-Werror=unused-variable]
  635 |   int s = snprintf(ctu_buf,4,"%d",ctuSize);
      |       ^